// Default sync URLs (pre-filled in Settings)
const DEFAULT_SHEET_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQlftn-2fPVpc-hrddDbFbrV36Jdliy6msnvdsmbxpSm_LawqvyC5BjT6eITZUo9DI39xud_tQwP9L3/pub?gid=0&single=true&output=csv';
const DEFAULT_WRITE_URL = 'https://script.google.com/macros/s/AKfycbx7spJR3WHSi6Hpz0AYFwP8UAgkdldpD_q6tN0H96_nltHdqqQG7_N5pnPinOEYJNlgZQ/exec';

const tourData = [
    { id: 1, date: "2026-03-04", city: "Tokyo", airport: "NRT", country: "Japan", venue: "Antiknock", name: "Baba", deal: "TESTEST", openers: "venue provides", schedule: "SCHD TST", email: "ANTIKNOCK <info@antiknock.net>", phone: "111-222-3333", flight: "March 2nd: YVR-NRT 9:35 ZG021 $650 (AC)", status: "TEST", hotel: "Agoda: Hotel&Co. Sagami", visaCDN: "Visa-Free", visaMEX: "Visa-Free", visaNote: "VISA Additional Info TST" },
    { id: 2, date: "2026-03-05", city: "Mito", airport: "NRT", country: "Japan", venue: "Sonic", name: "Otsu", deal: "Venue provides", hotel: "Agoda: Mito Daiichi Hotel" },
    { id: 3, date: "2026-03-06", city: "Tokyo", airport: "NRT", country: "Japan", venue: "GODZ", deal: "Venue provides", email: "IG", hotel: "We book" },
    { id: 4, date: "2026-03-07", city: "Niigata", airport: "KIJ", country: "Japan", venue: "Woodys", deal: "Venue provides", hotel: "We book" },
    { id: 5, date: "2026-03-08", city: "Osaka", airport: "KIX", country: "Japan", venue: "Sengoku Daitouryo", deal: "Venue provides", email: "IG", hotel: "We book" },
    { id: 6, date: "2026-03-09", city: "", airport: "KIX", country: "Japan", hotel: "We book" },
    { id: 7, date: "2026-03-10", city: "", airport: "KIX", country: "Japan", hotel: "We book" },
    { id: 8, date: "2026-03-11", city: "", airport: "KIX", country: "Japan", hotel: "We book" },
    { id: 9, date: "2026-03-12", city: "Fukuoka", airport: "FUK", country: "Japan", venue: "Utero", email: "IG", hotel: "We book" },
    { id: 10, date: "2026-03-13", city: "", airport: "FUK", country: "Japan", flight: "FUK-OKA 13:55 ANA1211 ($92) 888137862", status: "Booked", hotel: "We book" },
    { id: 11, date: "2026-03-14", city: "Okinawa", airport: "OKA", country: "Japan", venue: "Remy's", name: "Remy", deal: "Venue provides", email: "IG", hotel: "We book", visaCDN: "Visa-Free", visaMEX: "Visa Required", visaNote: "(acquired)" },
    { id: 12, date: "2026-03-15", city: "Kaohsiung", airport: "KHH", country: "Taiwan", venue: "Paramount", deal: "50% of door", openers: "Youth Tear Bomb, Hehehaha", flight: "OKA-KHH 11:50 SL0391 ($223)", status: "Booked", hotel: "We book" },
    { id: 13, date: "2026-03-16", city: "Hengchun", airport: "HCN", country: "Taiwan", venue: "Shore Bar", hotel: "Apt. above venue" },
    { id: 14, date: "2026-03-17", city: "", airport: "HCN", country: "Taiwan", hotel: "Apt. above venue" },
    { id: 15, date: "2026-03-18", city: "Taichung", airport: "RMQ", country: "Taiwan", venue: "Sound Live House", deal: "door split after 10th ticket", openers: "Venue provides", hotel: "We book" },
    { id: 16, date: "2026-03-19", city: "Taipei", airport: "TPE", country: "Taiwan", venue: "Revolver", name: "Dan", deal: "40% of door", openers: "Greasy Alley (TBC), Toxic Bald (TBC)", schedule: "SC: 5pm, D: 730, S: 8pm", phone: "(886) 910911907", hotel: "We book" },
    { id: 17, date: "2026-03-20", city: "Hong Kong", airport: "HKG", country: "Hong Kong", venue: "Aftermath", deal: "Venue provides", flight: "TPE-HKG 11:50 HX253 ($134)", status: "F4V9HV", hotel: "We book", visaCDN: "Visa-Free", visaMEX: "Visa-Free" },
    { id: 18, date: "2026-03-21", city: "Ulaanbaatar", airport: "UBN", country: "Mongolia", venue: "Republik", name: "Tugsuo", email: "FB", flight: "HKG-UBN ($340)", status: "EOSB4C", hotel: "Venue provides", visaCDN: "Visa-Free", visaMEX: "E-Visa", visaNote: "https://evisa.mn/en" },
    { id: 19, date: "2026-03-22", city: "", airport: "UBN", country: "Mongolia", hotel: "Venue provides" },
    { id: 20, date: "2026-03-23", city: "", airport: "UBN", country: "Mongolia", flight: "UBN-PEK 18:55 MR801 ($220)", status: "DQ2TYQ", hotel: "We book" },
    { id: 21, date: "2026-03-24", city: "Beijing", airport: "PEK", country: "China", venue: "Shut Up Live", name: "Donatella", deal: "Bar split", openers: "venue find", address: "75 Wudaoying Hutong", hotel: "We book", visaCDN: "Visa-free", visaMEX: "Visa Required", visaNote: "(acquired)" },
    { id: 22, date: "2026-03-25", city: "Zhengzhou", airport: "CGO", country: "China", venue: "7LiveHouse", hotel: "We book" },
    { id: 23, date: "2026-03-26", city: "Wuhan", airport: "WUH", country: "China", venue: "M&Ms", hotel: "We book" },
    { id: 24, date: "2026-03-27", city: "Chengdu", airport: "CTU", country: "China", venue: "Jah Bar", deal: "100% of door", hotel: "We book" },
    { id: 25, date: "2026-03-28", city: "Chongqing", airport: "CKG", country: "China", venue: "PUNK FEST", name: "Chenfu", deal: "3000 RMB + Hotel", hotel: "Venue provides" },
    { id: 26, date: "2026-03-29", city: "", airport: "CKG", country: "China", deal: "Hotel by CQPF", hotel: "Venue provides" },
    { id: 27, date: "2026-03-30", city: "Indonesia", airport: "CGK", country: "Indonesia", deal: "Stay at Gaus'", flight: "CKG-CGK 11:00 MF8673 ($680)", hotel: "Gaus' House", visaCDN: "Visa on Arrival", visaMEX: "Visa on Arrival" },
    { id: 28, date: "2026-03-31", city: "Cianjur", airport: "CGK", country: "Indonesia", venue: "JMC", deal: "Stay at Gaus'", hotel: "Gaus' House" },
    { id: 29, date: "2026-04-01", city: "Bogor", airport: "CGK", country: "Indonesia", venue: "Prigel Cafe", deal: "Stay at Gaus'", hotel: "Gaus' House" },
    { id: 30, date: "2026-04-02", city: "Jakarta", airport: "CGK", country: "Indonesia", deal: "Stay at Gaus'", email: "Kristoff's bday", hotel: "Gaus' House" },
    { id: 31, date: "2026-04-03", city: "Phnom Penh", airport: "KTI", country: "Cambodia", venue: "Cloud", deal: "free accom", openers: "Venue provide", email: "Sophie's bday", flight: "CGK-KTI 11:35 ($158) QZ474", status: "XJCLUH", hotel: "Venue provides", visaCDN: "Visa on Arrival", visaMEX: "Visa on Arrival" },
    { id: 32, date: "2026-04-04", city: "Bangkok", airport: "DMK", country: "Thailand", venue: "Immortal", name: "Lakfah", openers: "Strangle", email: "FB", flight: "KTI-DMK 9:45 ($146) FD609", status: "PY348C", hotel: "We book", visaCDN: "Visa Free", visaMEX: "Visa Free" },
    { id: 33, date: "2026-04-05", city: "", airport: "DMK", country: "Thailand", hotel: "We book" },
    { id: 34, date: "2026-04-06", city: "", airport: "DMK", country: "Thailand", hotel: "We book" },
    { id: 35, date: "2026-04-07", city: "", airport: "DMK", country: "Thailand", flight: "DMK-KTM 11:10 SL220 ($197)", status: "ORHRKH", notes: "Flight changed to next day?", visaCDN: "Visa on Arrival", visaMEX: "Visa on Arrival" },
    { id: 36, date: "2026-04-08", city: "", airport: "KTM", country: "Nepal" },
    { id: 37, date: "2026-04-09", city: "Kathmandu", airport: "KTM", country: "Nepal", venue: "Beers n Cheers", name: "Ritavrat", openers: "Strangle" },
    { id: 38, date: "2026-04-10", city: "Delhi", airport: "DEL", country: "India", venue: "The Piano Man", name: "Arjun", deal: "free accom, 70%", openers: "Venue provides 1", schedule: "Need E-Business visa, venue will provide letter of invitation", flight: "KTM-DEL 6:30 AI0224 ($118)", status: "YZJUGF", hotel: "Venue provide", notes: "Fight changed to 6:45am", visaCDN: "E-Visa", visaMEX: "E-Visa", visaNote: "https://indianvisaonline.gov.in/visa/tvoa.html" },
    { id: 39, date: "2026-04-11", city: "Bangalore", airport: "BLR", country: "India", venue: "Fandom", flight: "DEL-BLR 9:30-12:25 AI2415 ($99)", status: "FR1LNQ", hotel: "We book" },
    { id: 40, date: "2026-04-12", city: "Mumbai", airport: "BOM", country: "India", flight: "BLR-BOM 11:25 6E 5011 ($90)", status: "OD7HPK", hotel: "We book" },
    { id: 41, date: "2026-04-13", city: "", airport: "BOM", country: "India", hotel: "We book" },
    { id: 42, date: "2026-04-14", city: "", airport: "BOM", country: "India", flight: "BOM-DXB 14:55 6E 1453 ($228)", status: "SBEE5A", hotel: "We book", visaCDN: "Visa Free", visaMEX: "Visa Free" },
    { id: 43, date: "2026-04-15", city: "Dubai", airport: "DXB", country: "UAE", venue: "Jimmy Dix", hotel: "We book" },
    { id: 44, date: "2026-04-16", city: "", airport: "DXB", country: "UAE", flight: "SHJ-ERB 9:40 G9357 ($320)", status: "6HTCX6", hotel: "Venue provide", visaCDN: "E-Visa", visaMEX: "E-Visa", visaNote: "https://visit.gov.krd/" },
    { id: 45, date: "2026-04-17", city: "Erbil", airport: "EBL", country: "Iraq", hotel: "Venue provide" },
    { id: 46, date: "2026-04-18", city: "Beirut", airport: "BEY", country: "Lebanon", venue: "Zico House", flight: "ERB-BEY 15:15-17:05 ME0325 ($191)", status: "C2TXUL", hotel: "Venue provide", visaCDN: "Visa-Free", visaMEX: "Visa-Free" },
    { id: 47, date: "2026-04-19", city: "Damascus", airport: "DAM", country: "Syria", venue: "Floyd Pub", flight: "BUS to Damascus", visaCDN: "E-Visa", visaMEX: "E-Visa", visaNote: "https://evisa.sy/" },
    { id: 48, date: "2026-04-20", city: "", airport: "DAM", country: "Syria" },
    { id: 49, date: "2026-04-21", city: "", airport: "DAM", country: "Syria", flight: "BUS to Beirut" },
    { id: 50, date: "2026-04-22", city: "", airport: "BEY", country: "Lebanon", flight: "BEY-AYT-TBS 20:45-22:10/3:40-6:45 PC1825,PC1840 ($233)", status: "1ZPHZD/1ZPHUW", notes: "SELF TRANSFER, COLLECT BAGS", visaCDN: "Visa-Free", visaMEX: "Turkiye: E-Visa (free)", visaNote: "https://dtvgroup.com.tr/" },
    { id: 51, date: "2026-04-23", city: "Kutaisi", airport: "KUT", country: "Georgia", venue: "Riff Raff", flight: "Rent car at TBS", hotel: "Venue provide", visaCDN: "Visa-Free", visaMEX: "Visa-Free" },
    { id: 52, date: "2026-04-24", city: "Tbilisi", airport: "TBS", country: "Georgia", venue: "Revolution", flight: "Bus Kutaisi–Tbilisi" },
    { id: 53, date: "2026-04-25", city: "Yerevan", airport: "EVN", country: "Armenia", venue: "Muha Punk Bar", email: "IG", flight: "Bus Tbilisi–Yerevan ($42)", hotel: "We book", visaCDN: "E-Visa", visaMEX: "E-Visa", visaNote: "https://evisa.mfa.am/" },
    { id: 54, date: "2026-04-26", city: "Istanbul", airport: "SAW", country: "Turkey", venue: "Dorock", flight: "EVN-SAW 6:30-8:00 PC551 ($149)", status: "1ZPHR6", hotel: "We book", visaCDN: "Visa-Free", visaMEX: "Turkiye: E-Visa (free)" },
];
